# в закомментированных строках находятся критически важные переменные, например пути на хостовой машине которые могут быть удалены при сборке
# будьте осторожны при проставлении данных путей
kind: pipeline
name: deploy

trigger:
  branch:
  - prod
  event:
  - push

steps:
- name: Build and copy to host machine
  image: node
  volumes:
  - name: Host alias
    path: /drone/src/host-alias
  commands:
  - npm install
  - npm run build
  - rm -rf /drone/src/host-alias/dist # директория со старой сборкой, удаляем dist из /drone/src/host-alias
  - cp -r /drone/src/dist /drone/src/host-alias # копируем новый dist в /drone/src/host-alias
  when:
    branch:
    - prod # на какой ветке должно сработать событие
    event:
    - push # по какому события запускается пайплайн

volumes:
- name: Host alias
  host:
    # путь на хостовой машине, будьте осторожны, дрон сможет запускать любые linux команды внутри данной директории
    path: /var/www/coding-cats/crm-front # директория с которой работаем
